module(name = "faster-swiper")

bazel_dep(name = "apple_support", version = "2.5.3")
bazel_dep(name = "rules_cc", version = "0.2.18")
bazel_dep(name = "rules_apple", version = "4.5.3")
bazel_dep(name = "rules_swift", version = "3.6.1")
bazel_dep(name = "rules_xcodeproj", version = "4.0.1")
bazel_dep(name = "abseil-cpp", version = "20260107.1")
git_override(
    module_name = "abseil-cpp",
    commit = "1ea7b9254fd6f29d72069473856d58837d19cbfc",
    remote = "https://github.com/abseil/abseil-cpp.git",
)

bazel_dep(name = "googletest", version = "1.17.0.bcr.2")
bazel_dep(name = "nlohmann_json", version = "3.12.0.bcr.1")
bazel_dep(name = "protobuf", version = "34.1")
bazel_dep(name = "rules_swift_package_manager", version = "1.17.1")
bazel_dep(name = "rules_shell", version = "0.8.0")
bazel_dep(name = "aspect_rules_lint", version = "2.5.2")
bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "toolchains_llvm", version = "1.7.0")

# Fixes some issue with transitive rules_android dependency
bazel_dep(name = "rules_android", version = "0.7.2")

# LLVM toolchain for clang-tidy
llvm = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm")
llvm.toolchain(
    cxx_standard = {"": "c++23"},
    llvm_versions = {
        "": "21.1.8",
    },
    stdlib = {"": "builtin-libc++"},
)
use_repo(llvm, "llvm_toolchain", "llvm_toolchain_llvm")

swift_deps = use_extension(
    "@rules_swift_package_manager//:extensions.bzl",
    "swift_deps",
)
swift_deps.from_package(
    declare_swift_deps_info = True,
    resolved = "//:Package.resolved",
    swift = "//:Package.swift",
)
use_repo(
    swift_deps,
    "swift_deps_info",
    "swift_package",
    "swiftpkg_swift_protobuf",
)

# Override needed because the latest BCR release isn't compatible with Bazel 9
bazel_dep(name = "magic_enum")
git_override(
    module_name = "magic_enum",
    commit = "7d87efb4a3dddbbe8caa9ca14eff05ede1102ab8",
    remote = "https://github.com/Neargye/magic_enum.git",
)

# Fork for Hedron's Compile Commands Extractor for Bazel.
# Fork: https://github.com/claymaks/bazel-compile-commands-extractor
# Original: https://github.com/hedronvision/bazel-compile-commands-extractor
bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
git_override(
    module_name = "hedron_compile_commands",
    commit = "818899d71ed956ed41a7c4775e97846df03e8338",
    remote = "https://github.com/claymaks/bazel-compile-commands-extractor.git",
)

bazel_dep(name = "mgbowen_create_dmg")
git_override(
    module_name = "mgbowen_create_dmg",
    commit = "a5e45002a9d301e7e7fb6529bd2c721f8a9ae036",
    remote = "https://github.com/mgbowen/bazel-create-dmg.git",
)
