module(name = "faster-swiper")

bazel_dep(name = "apple_support", version = "2.9.1")
bazel_dep(name = "rules_cc", version = "0.2.25")
bazel_dep(name = "rules_apple", version = "5.2.0")
bazel_dep(name = "rules_swift", version = "4.1.2")
bazel_dep(name = "rules_xcodeproj", version = "4.1.0")
bazel_dep(name = "abseil-cpp", version = "20260817.0")
bazel_dep(name = "magic_enum", version = "0.9.8")
bazel_dep(name = "googletest", version = "1.18.0.bcr.1")
bazel_dep(name = "nlohmann_json", version = "3.12.0.bcr.2")
bazel_dep(name = "protobuf", version = "36.2")
bazel_dep(name = "grpc", version = "1.84.0")
bazel_dep(name = "rules_swift_package_manager", version = "1.25.0")
bazel_dep(name = "rules_shell", version = "0.8.0")
bazel_dep(name = "aspect_rules_lint", version = "2.9.1")
bazel_dep(name = "bazel_skylib", version = "1.9.2")
bazel_dep(name = "toolchains_llvm", version = "1.11.0")

# LLVM toolchain for clang-format, clang-tidy, etc.
llvm = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm")
llvm.toolchain(
    cxx_standard = {"": "c++23"},
    llvm_versions = {
        "": "23.1.2",
    },
    stdlib = {"": "builtin-libc++"},
)
use_repo(llvm, "llvm_toolchain", "llvm_toolchain_llvm")

swift_deps = use_extension(
    "@rules_swift_package_manager//:extensions.bzl",
    "swift_deps",
)
swift_deps.from_package(
    declare_swift_deps_info = True,
    resolved = "//:Package.resolved",
    swift = "//:Package.swift",
)
use_repo(
    swift_deps,
    "swift_deps_info",
    "swift_package",
    "swiftpkg_swift_protobuf",
)

# Fork for Hedron's Compile Commands Extractor for Bazel.
# Fork: https://github.com/claymaks/bazel-compile-commands-extractor
# Original: https://github.com/hedronvision/bazel-compile-commands-extractor
bazel_dep(name = "hedron_compile_commands")
git_override(
    module_name = "hedron_compile_commands",
    commit = "818899d71ed956ed41a7c4775e97846df03e8338",
    remote = "https://github.com/claymaks/bazel-compile-commands-extractor.git",
)

bazel_dep(name = "mgbowen_bazel_create_dmg")
git_override(
    module_name = "mgbowen_bazel_create_dmg",
    commit = "352250f742a82a5c6f4d02d05c7bf187a56c5ca9",
    remote = "https://github.com/mgbowen/bazel-create-dmg.git",
)
