load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "const",
    hdrs = ["const.h"],
    deps = [
        "//src:cf-util",
        "//src:const",
        "//src:event",
        "//src:macos-private",
        "//src:mission-control",
        "//src:periodic-timer",
        "//src:space-state",
        "//src:string-util",
        "@abseil-cpp//absl/cleanup",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/synchronization",
    ],
)

cc_library(
    name = "axis-adapter",
    srcs = ["axis-adapter.cc"],
    hdrs = ["axis-adapter.h"],
    deps = [
        "//src:cf-util",
        "//src:const",
        "//src:event",
        "//src:macos-private",
        "//src:mission-control",
        "//src:periodic-timer",
        "//src:space-state",
        "//src:string-util",
        "@abseil-cpp//absl/cleanup",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/synchronization",
    ],
)

cc_library(
    name = "space-switch-operation",
    srcs = ["space-switch-operation.cc"],
    hdrs = ["space-switch-operation.h"],
    deps = [
        ":axis-adapter",
        ":const",
        "//src:cf-util",
        "//src:const",
        "//src:event",
        "//src:macos-private",
        "//src:mission-control",
        "//src:periodic-timer",
        "//src:space-state",
        "//src:string-util",
        "@abseil-cpp//absl/cleanup",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/synchronization",
    ],
)
