load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "const",
    hdrs = ["const.h"],
)

cc_library(
    name = "deferred-position",
    srcs = ["deferred-position.cc"],
    hdrs = ["deferred-position.h"],
    deps = [
        ":const",
        "//src:cf-util",
        "//src:event",
        "//src:macos-private",
        "//src:mission-control",
        "//src:periodic-timer",
        "//src:space-state",
        "//src:string-util",
        "@abseil-cpp//absl/cleanup",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@abseil-cpp//absl/synchronization",
    ],
)

cc_library(
    name = "axis-adapter",
    srcs = ["axis-adapter.cc"],
    hdrs = ["axis-adapter.h"],
    deps = [
        ":const",
        "//src:cf-util",
        "//src:event",
        "//src:macos-private",
        "//src:mission-control",
        "//src:periodic-timer",
        "//src:space-state",
        "//src:string-util",
        "@abseil-cpp//absl/cleanup",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:status_macros",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/synchronization",
    ],
)

cc_library(
    name = "space-switch-operation",
    srcs = ["space-switch-operation.cc"],
    hdrs = ["space-switch-operation.h"],
    deps = [
        ":axis-adapter",
        ":const",
        ":deferred-position",
        "//src:cf-util",
        "//src:event",
        "//src:gesture-serialization",
        "//src:macos-private",
        "//src:mission-control",
        "//src:periodic-timer",
        "//src:space-state",
        "//src:string-util",
        "@abseil-cpp//absl/cleanup",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:status_macros",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/synchronization",
    ],
)

cc_library(
    name = "physical-event-handler",
    srcs = ["physical-event-handler.cc"],
    hdrs = ["physical-event-handler.h"],
    deps = [
        ":axis-adapter",
        ":const",
        ":space-switch-operation",
        ":swipe-animator",
        "//src:channel",
        "//src:enum-util",
        "//src:event",
        "//src:hotkeys",
        "//src:macos-private",
        "//src:mission-control",
        "//src:proto-util",
        "//src:space-state",
        "//src:variant-util",
        "//src/public:fasterswiper_cc_proto",
        "@abseil-cpp//absl/cleanup",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/log:vlog_is_on",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:status_macros",
        "@abseil-cpp//absl/status:statusor",
        "@magic_enum",
    ],
)

cc_library(
    name = "swipe-animator",
    srcs = ["swipe-animator.cc"],
    hdrs = ["swipe-animator.h"],
    deps = [
        ":space-switch-operation",
        "//src:easing",
        "//src:periodic-timer",
        "@abseil-cpp//absl/cleanup",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/memory",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:status_macros",
        "@abseil-cpp//absl/status:statusor",
        "@magic_enum",
    ],
)
