load("@protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@protobuf//bazel:proto_library.bzl", "proto_library")
load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_swift//proto:proto.bzl", "swift_proto_library")
load("@rules_swift//swift:swift_interop_hint.bzl", "swift_interop_hint")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "public",
    srcs = ["fasterswiper.cc"],
    hdrs = ["fasterswiper.h"],
    aspect_hints = [":c_api_swift_interop"],
    visibility = ["//visibility:public"],
    deps = [
        ":fasterswiper_cc_proto",
        "//src:CoreFoundation",
        "//src:easing",
        "//src:event-tap-manager",
        "//src:macos-private",
        "//src:notifications",
        "//src:physical-event-handler",
        "//src:version",
        "@abseil-cpp//absl/flags:parse",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/synchronization",
    ],
)

swift_interop_hint(
    name = "c_api_swift_interop",
    module_name = "FasterSwiper_CApi",
)

proto_library(
    name = "fasterswiper_proto",
    srcs = ["fasterswiper.proto"],
    deps = [
        "@protobuf//:duration_proto",
    ],
)

cc_proto_library(
    name = "fasterswiper_cc_proto",
    deps = [":fasterswiper_proto"],
)

swift_proto_library(
    name = "fasterswiper_swift_proto",
    module_name = "FasterSwiper_Proto",
    protos = [":fasterswiper_proto"],
    deps = [
        "@protobuf//:duration_cc_proto",
    ],
)
