load("@protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@protobuf//bazel:proto_library.bzl", "proto_library")
load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_swift//proto:proto.bzl", "swift_proto_compiler", "swift_proto_library")
load("@rules_swift//swift:swift_interop_hint.bzl", "swift_interop_hint")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "public",
    srcs = ["fasterswiper.cc"],
    hdrs = ["fasterswiper.h"],
    aspect_hints = [":c_api_swift_interop"],
    visibility = ["//visibility:public"],
    deps = [
        ":fasterswiper_cc_proto",
        "//src:CoreFoundation",
        "//src:easing",
        "//src:event-tap-manager",
        "//src:macos-private",
        "//src:version",
        "//src/engine:physical-event-handler",
        "@abseil-cpp//absl/flags:parse",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/synchronization",
    ],
)

swift_interop_hint(
    name = "c_api_swift_interop",
    module_name = "FasterSwiper_CApi",
)

proto_library(
    name = "fasterswiper_proto",
    srcs = ["fasterswiper.proto"],
    deps = [
        "@protobuf//:duration_proto",
    ],
)

cc_proto_library(
    name = "fasterswiper_cc_proto",
    deps = [":fasterswiper_proto"],
)

swift_proto_compiler(
    name = "swift_protobuf_spm",
    plugin = "@swiftpkg_swift_protobuf//:protoc-gen-swift",
    plugin_name = "swift",
    plugin_option_allowlist = [
        "Visibility",
        "FileNaming",
        "ProtoPathModuleMappings",
        "ImplementationOnlyImports",
        "UseAccessLevelOnImports",
    ],
    plugin_options = {
        "Visibility": "Public",
        "FileNaming": "FullPath",
    },
    suffixes = [".pb.swift"],
    visibility = ["//visibility:public"],
    deps = ["@swiftpkg_swift_protobuf//:SwiftProtobuf"],
)

swift_proto_library(
    name = "fasterswiper_swift_proto",
    compilers = [":swift_protobuf_spm"],
    module_name = "FasterSwiper_Proto",
    protos = [":fasterswiper_proto"],
    deps = [
        "@protobuf//:duration_cc_proto",
    ],
)
