name: Build .app

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-26
    outputs:
      artifact-name: ${{ steps.build.outputs.artifact_name }}
    steps:
      - name: Checkout FasterSwiper
        uses: actions/checkout@v6

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@c5acdfb288317d0b5c0bbd7a396a3dc868bb0f86
        with:
          disk-cache: true
          repository-cache: true

      - name: Build App
        id: build
        run: |
          build_opts='--compilation_mode=opt //src/app:FasterSwiper_app'
          bazel build $build_opts
          ZIP_PATH=$(bazel cquery --output=files $build_opts)
          mkdir -p out
          unzip "$ZIP_PATH" -d out

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FasterSwiper_app.zip
          path: out/
          retention-days: 90
