name: Build .app

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-26
    outputs:
      artifact-name: ${{ steps.build.outputs.artifact_name }}
    steps:
      - name: Checkout FasterSwiper
        uses: actions/checkout@v6

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@c5acdfb288317d0b5c0bbd7a396a3dc868bb0f86
        with:
          disk-cache: true
          repository-cache: true

      - name: Build App
        id: build
        run: |
          build_opts='--compilation_mode=opt //src/app:FasterSwiper_dmg'
          bazel build $build_opts
          DMG_PATH=$(bazel cquery --output=files $build_opts)
          echo "DMG_PATH=$DMG_PATH" >> $GITHUB_ENV
          echo "artifact_name=FasterSwiper.dmg" >> $GITHUB_OUTPUT

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.artifact_name }}
          path: ${{ env.DMG_PATH }}
          retention-days: 1

  release:
    needs: build
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact-name }}

      - name: Prepare Release Asset
        run: |
          mv FasterSwiper.dmg FasterSwiper-${{ github.ref_name }}.dmg

      - name: Create GitHub Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda
        with:
          files: FasterSwiper-${{ github.ref_name }}.dmg
          generate_release_notes: true
